### ISSUE TITLE
Pickaxe isn't a Pickaxe (0.4.0)

### ISSUE THREAD

**Issue by Drakoflame** [mickelus/tetra-resources#3]
I recently downloaded the latest version (0.4.0) because I saw that there was an "Axe" and "Pickaxe" version of the tools available, and I was super excited to use them. They were quite easy to make, quickly turning my wooden axe into a stone axe/pickax (axe head with pickaxe head). It seemed a little slow to mine up the work benches I'd placed, but I figured thats because it was a dual-sided tool, because it worked just fine on trees. My next step was to mine up some stone, which was fairly easy and quick, but then I noticed that the tool hadn't taken ANY durability at all, curiosity kicked in and I used veinminer... and nearly destroyed a mountain before I realized the tool still wasn't taking durability damage. "Okay, thats fine, its an alpha mod, bugs are to be expected!" Upon smacking an animal with the tool though, it did take durability damage, "Okay... it IS an alpha... maybe the developer hadn't realized this yet?". 

Now, I would have happily continued using the mod from this point, having a fancy tool to smack things with, but as I was running, I kept thinking about what kinds of materials I could use to do things, like the handles, blades, mallet heads etc, etc. I came across a Recurrent Complex Fossil structure, with my pick-axe in hand, I began to mine.... and mine.... and mine... until it finally broke, asif punching by hand, dropping nothing... the pick-axe, wasn't a pickaxe... so I threw down my benches, swapped the the heads to both be pickaxe heads, and tried agian, same thing. It took to long to mine and didn't drop anything... At this point I was a little frustrated and just wanted to mine some bone blocks to see if thats what I needed to make a bone handle, so I cheated in some iron, gold, diamonds... none of it worked, it all acted as if I were mining by hand, so I said screw it, and cheated in some bones, bone blocks, bonemeal, aaaand none of it worked for the bone handle... on any tools to make it worse. 

I didn't bother testing the other stones, I was a little peeved and just felt like I should bring it up as a bug. I also really wanted to try out the Heavy Blade weapons but, you can't currently make a Tier 4 mallet (which is obsidian, which requires a tier 4 hammer to make... but.. you can't because... I'm sure you get the point), and I know that you stated that the way to obtain this tier four hammer hasn't yet been implemented.

**Condensed version:**
Tried to mine something other than stone with Tetra 'pickaxe', didn't work. Tried using wood, stone, iron, diamond heads, nothing worked. Also couldn't change haft/handle material to anything other than wood and iron. Tested on 0.4.0 latest release

**Comment by mickelus** [comment]
Most of your issues should be resolved in [0.4.1](https://minecraft.curseforge.com/projects/tetra/files/2545094). Did you try crafting a heavy blade? It should only be the obsidian blade that requires a tier 4 hammer.

**Comment by Drakoflame** [comment]
ey', I did try crafting a heavy blade, both stone and iron (IIRC you can't make a wooden one). Unless I saw things wrong.

I'll wait for the next update to go out before trying things again, here's to hoping that I can use this mod as intended once again!

P.S. Shovels/Hoes when?

**Comment by Drakoflame** [comment]
Alright! I'm back, and going to stay on this thread because still an issue...

So I made a 'stone' pickaxe, and everything was working fantabulous (was even able to make a stone greatsword with a level 2 mallet), had a decent mining speed as well (not like punching stone with my fist), but when I went to pick up my furnaces to find a better place to live, other than the inside of a cave, I noticed on my Hwyla (Here's what your looking at mod, the spiritual successor to Waila), that it said the furnace was "not currently harvestable", and I immediatly knew that it was an issue... ontop of that, I went to mine some chalk (from Earthworks), and it said the same thing, not harvestable, even terracotta wasn't harvestable, it seemed like _ONLY_ stone was harvestable (granite, andesite, etc) but nothing else...

**Comment by mickelus** [comment]
There are a few different ways to calculate if a block is harvestable and I missed one of them. Ores, stone, rails and a few other blocks should have been harvestable before. From 0.4.2 it should also be possible to harvest blocks such as furnaces, hoppers, prismarine and terracotta.

**Comment by Drakoflame** [comment]
so far it seems to be working! (I know its a few days later) but yea, things seem to work for now! thanks for the quick fix man!
